In [1]:
#numpy means the numerical python which basically work with different types of numerical data
import numpy as np

In [2]:
l = [1, 2, 3, 4]

In [3]:
ar = np.array(l)

In [4]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1, 2],
         [3, 4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.asanyarray(l) #asanyarray convert into single dimension array

array([1, 2, 3, 4])

In [9]:
type(np.asanyarray(l))

numpy.ndarray

In [10]:
a = [2, 3, 4]

In [11]:
np.asanyarray(a)

array([2, 3, 4])

In [12]:
b = np.matrix(l) #convert into 2 dim array ie. matrix

In [13]:
b

matrix([[1, 2, 3, 4]])

In [14]:
c = a

In [15]:
c

[2, 3, 4]

In [16]:
a

[2, 3, 4]

In [17]:
c[0] = 100

In [18]:
c

[100, 3, 4]

In [19]:
a

[100, 3, 4]

- Here, we can see that modification in one reflects the changes in data into another array

In [21]:
d = np.copy(a)

In [22]:
d

array([100,   3,   4])

In [23]:
a

[100, 3, 4]

In [24]:
a[1] = 498

In [25]:
a

[100, 498, 4]

In [26]:
d

array([100,   3,   4])

- Here, changes in one don't relate other to be changed or modified

In [27]:
np.fromfunction(lambda i, j: i==j, (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
np.fromfunction(lambda i, j: i*j, (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [29]:
iterable = (i*i for i in range(5))

In [30]:
iterable

<generator object <genexpr> at 0x00000239D2811F20>

In [31]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [32]:
np.fromstring("234 2342", sep = " ")

array([ 234., 2342.])

In [34]:
np.fromstring("222, 453", sep = ",")

array([222., 453.])

In [35]:
#numpy data type
l = [2, 3, 4, 5, 6]

In [36]:
ar = np.array(l)

In [37]:
ar

array([2, 3, 4, 5, 6])

In [38]:
ar.ndim

1

In [39]:
ar2 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

In [40]:
ar2.ndim

2

In [41]:
ar.size

5

In [42]:
ar2.size

8

In [43]:
ar.shape

(5,)

In [44]:
ar2.shape

(2, 4)

In [47]:
ar.dtype, ar2.dtype

(dtype('int32'), dtype('int32'))

In [48]:
ar22 = np.array([[1.3, 4.3, 22],
                 [4, 32, 4.3]])

In [50]:
ar22.dtype

dtype('float64')

In [51]:
list(range(5))

[0, 1, 2, 3, 4]

In [52]:
list(range(0.1, 4)) #can't return the float value from range

TypeError: 'float' object cannot be interpreted as an integer

In [53]:
#arange used for float values
np.arange(2.3, 4.3)

array([2.3, 3.3])

In [54]:
np.arange(2.3, 4.3, 0.2)

array([2.3, 2.5, 2.7, 2.9, 3.1, 3.3, 3.5, 3.7, 3.9, 4.1])

In [55]:
list(np.arange(2.3, 4.3, 0.2))

[2.3,
 2.5,
 2.7,
 2.9000000000000004,
 3.1000000000000005,
 3.3000000000000007,
 3.500000000000001,
 3.700000000000001,
 3.9000000000000012,
 4.100000000000001]

In [57]:
np.linspace(1, 5, 10) #10 pieces between 1 to 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [59]:
np.linspace(1, 5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [61]:
np.zeros((3, 2)) #no of zeros in array form 2 dim

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [62]:
np.zeros((2, 3, 4)) #3 dim

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [63]:
np.zeros((2, 3, 4, 4)) #4 dim

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [64]:
np.ones(4)

array([1., 1., 1., 1.])

In [67]:
on = np.ones((3, 2))

In [68]:
on

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [66]:
np.ones((3, 2, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [69]:
on * 4

array([[4., 4.],
       [4., 4.],
       [4., 4.]])

In [70]:
on + 5

array([[6., 6.],
       [6., 6.],
       [6., 6.]])

In [71]:
np.empty((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.eye(7) #identity matrix

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [75]:
np.linspace(2, 5, 20) #Return evenly spaced numbers over a specified interval.

array([2.        , 2.15789474, 2.31578947, 2.47368421, 2.63157895,
       2.78947368, 2.94736842, 3.10526316, 3.26315789, 3.42105263,
       3.57894737, 3.73684211, 3.89473684, 4.05263158, 4.21052632,
       4.36842105, 4.52631579, 4.68421053, 4.84210526, 5.        ])

In [76]:
np.logspace(2, 5, 20) #Return numbers spaced evenly on a log scale.

array([   100.        ,    143.84498883,    206.91380811,    297.63514416,
          428.13323987,    615.84821107,    885.86679041,   1274.2749857 ,
         1832.98071083,   2636.65089873,   3792.69019073,   5455.59478117,
         7847.59970351,  11288.37891685,  16237.76739189,  23357.2146909 ,
        33598.18286284,  48329.30238572,  69519.27961776, 100000.        ])

In [78]:
import pandas as pd

In [79]:
arr = np.random.randn(3, 4) #Return a sample (or samples) from the "standard normal" distribution, where mean = 0 and std. var = 1

In [80]:
pd.DataFrame(arr)

0         1         2         3
0  0.246060 -0.204104  1.014605  0.939339
1  0.637151 -0.045316  0.125988 -0.264364
2 -0.357433  0.756572 -1.196924  1.330678

In [81]:
np.random.rand(3, 4) #Random values in a given shape.

array([[0.25470078, 0.07054109, 0.71218609, 0.65678421],
       [0.7203444 , 0.34910523, 0.98287715, 0.0636772 ],
       [0.08730483, 0.08176619, 0.17733403, 0.12032279]])

In [82]:
np.random.randint(1, 20, 20)

array([ 2,  3,  6, 17,  6,  1, 12, 13, 14, 14,  4,  3, 14, 18, 18, 17, 10,
       10, 19,  2])

In [83]:
np.random.randint(1, 20, (4, 3)) #Return random integers from `low` (inclusive) to `high` (exclusive).

array([[19,  2,  7],
       [ 9,  7, 18],
       [14, 12,  5],
       [ 3, 12,  9]])

In [85]:
pd.DataFrame(np.random.randint(1, 20, (400, 300)) )

0    1    2    3    4    5    6    7    8    9    ...  290  291  292  \
0      2   10   11    7   12   17    5    7    5   15  ...   16    8   14   
1      1   18    2   11   15   10   19    2    9    7  ...   14   19   15   
2      9   18    6    9    2    1    3    8    4   19  ...   18   14    6   
3      6    7    7   14   14    3   11    6    7    9  ...    2   14   10   
4     14    3    6    1    6    5    9    4   19    3  ...    8   16   14   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
395    2    2    7   16    9    4    1    4   10   11  ...    4    3    3   
396   18    6   19   15    2   12    6    2   17   19  ...    5   11    9   
397   11   16    7   18    4    3   11   19   18   14  ...   10   16   17   
398   18    5   15    3    3   17    4   14   15   15  ...   11    7    7   
399    3    2    8   13    3   17   17    8    1   15  ...   12   18    7   

     293  294  295  296  297  298  299  
0     10    7   17    3   10    1   15  
1      1   15    7    8    8    3    9  
2     13    7    8    1   10   17    2  
3     10    4   18    3    2   10   16  
4     11   16    8   19   15    1   13  
..   ...  ...  ...  ...  ...  ...  ...  
395    8    7    2    3    9    8    5  
396    7    1    7    3   12   13    1  
397    6   18   14   17   11    8   13  
398   12    2   10   13   14   10    2  
399    4   15   15   11    1   10   11  

[400 rows x 300 columns]

In [86]:
arr = np.random.rand(3, 4)

In [87]:
arr

array([[0.91610872, 0.19500712, 0.29322404, 0.65730964],
       [0.96347899, 0.64330574, 0.35571737, 0.30133377],
       [0.18237246, 0.99991609, 0.02584642, 0.51946122]])

In [94]:
arr = arr.reshape(6, 2)

In [99]:
arr

array([[0.91610872, 0.19500712],
       [0.29322404, 0.65730964],
       [0.96347899, 0.64330574],
       [0.35571737, 0.30133377],
       [0.18237246, 0.99991609],
       [0.02584642, 0.51946122]])

In [97]:
arr[1][1]

0.6573096367475846

In [100]:
arr[2:5, 1]

array([0.64330574, 0.30133377, 0.99991609])

In [104]:
arr = np.random.randint(1, 100, (5, 5))

In [105]:
arr

array([[38, 65, 92, 53, 26],
       [71,  3, 35, 31, 18],
       [24, 48, 17, 32, 11],
       [43, 44, 37, 85, 42],
       [71, 88,  3, 61, 22]])

In [109]:
arr[arr>50]

array([65, 92, 53, 71, 85, 71, 88, 61])

In [110]:
arr[2:4, [1, 2]] #we can ask for any subset of matrix where required

array([[48, 17],
       [44, 37]])

In [111]:
arr[0][0] = 5000 #means we can change it's elements

In [112]:
arr

array([[5000,   65,   92,   53,   26],
       [  71,    3,   35,   31,   18],
       [  24,   48,   17,   32,   11],
       [  43,   44,   37,   85,   42],
       [  71,   88,    3,   61,   22]])

In [117]:
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))
arr3 = np.random.randint(1, 3, (4, 3))

In [118]:
arr1

array([[2, 2, 2],
       [2, 2, 2],
       [1, 2, 2]])

In [119]:
arr2

array([[2, 2, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [120]:
#we can add two similar order matrix when we want
arr1 + arr2

array([[4, 4, 4],
       [4, 3, 3],
       [3, 4, 3]])

In [122]:
arr1 + arr3 #we can't add two diffrent type of order of matrices

ValueError: operands could not be broadcast together with shapes (3,3) (4,3) 

In [123]:
arr1 - arr2 #substraction execute from element to element

array([[ 0,  0,  0],
       [ 0,  1,  1],
       [-1,  0,  1]])

In [124]:
arr1 * arr2 #this muliplication is execute from element to element

array([[4, 4, 4],
       [4, 2, 2],
       [2, 4, 2]])

In [125]:
arr1/arr2 #division is execute from element to element

array([[1. , 1. , 1. ],
       [1. , 2. , 2. ],
       [0.5, 1. , 2. ]])

In [126]:
arr1@arr2 #@ is denote the matrix multiplication where row of 1st matrix multiply with column of 2nd matrix

array([[12, 10,  8],
       [12, 10,  8],
       [10,  8,  6]])

In [127]:
arr1 + 100 #we can add any integer to matrix, it's modifiable

array([[102, 102, 102],
       [102, 102, 102],
       [101, 102, 102]])

In [128]:
#numpy - Broadcasting
arr = np.zeros((4, 4))

In [129]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [130]:
row = np.array([1, 2, 3, 4])

In [131]:
row

array([1, 2, 3, 4])

In [133]:
row.shape

(4,)

In [132]:
arr + row #as row is horizontal, so the calulation is execute in horizontal manner

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [134]:
row.T #this row didn't transpose, as it is in 1-D array so 1-D array can't be in transpose mode

array([1, 2, 3, 4])

In [135]:
col = np.array([[1, 2, 3, 4]])

In [139]:
col = col.T

In [140]:
col

array([[1],
       [2],
       [3],
       [4]])

In [141]:
col.shape

(4, 1)

In [142]:
arr + col #as col is in vertical, so the calucation is also be in vertical manner.

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [144]:
arr = np.random.randint(1, 4, (3, 4))

In [145]:
arr

array([[3, 2, 1, 1],
       [1, 1, 1, 2],
       [2, 1, 3, 1]])

In [146]:
np.sqrt(arr) #square root of each element

array([[1.73205081, 1.41421356, 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.41421356],
       [1.41421356, 1.        , 1.73205081, 1.        ]])

In [147]:
np.exp(arr) #exponential of each element

array([[20.08553692,  7.3890561 ,  2.71828183,  2.71828183],
       [ 2.71828183,  2.71828183,  2.71828183,  7.3890561 ],
       [ 7.3890561 ,  2.71828183, 20.08553692,  2.71828183]])

In [148]:
np.log10(arr) #logarithm order of 10 of each element present in matrix

array([[0.47712125, 0.30103   , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.30103   ],
       [0.30103   , 0.        , 0.47712125, 0.        ]])

In [149]:
#Numpy - array Manipulation
arr = np.random.randint(1, 10, (3, 4))
arr

array([[5, 7, 6, 2],
       [9, 6, 6, 6],
       [5, 3, 5, 7]])

In [150]:
arr.shape

(3, 4)

In [151]:
arr.reshape(6, 2)

array([[5, 7],
       [6, 2],
       [9, 6],
       [6, 6],
       [5, 3],
       [5, 7]])

In [152]:
arr.reshape(4, 2) #we can't reshape it as 4*2 = 8 elements whereas arr has 3*4 = 12 elements which can't be stored into (4, 2)

ValueError: cannot reshape array of size 12 into shape (4,2)

In [153]:
arr.reshape(2, -34334343) #it will automatically understand that j value will be 6 as we state i value

array([[5, 7, 6, 2, 9, 6],
       [6, 6, 5, 3, 5, 7]])

In [155]:
arr.flatten() #it's used to convert n - dim array to 1-D array

array([5, 7, 6, 2, 9, 6, 6, 6, 5, 3, 5, 7])

In [156]:
arr1 = np.array([1, 2, 3, 3, 4])

In [157]:
arr1.ndim

1

In [158]:
np.expand_dims(arr1, axis = 1) #converting 1-D array to 2-D array with transpose into vertical order

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [159]:
np.expand_dims(arr1, axis = 0)#converting 1-D array to 2-D array without transpose into vertical order

array([[1, 2, 3, 3, 4]])

In [160]:
data = np.array([[1], [2], [3]])

In [161]:
data

array([[1],
       [2],
       [3]])

In [162]:
data.squeeze() #converting 2-D array into 1-D array

array([1, 2, 3])

In [163]:
arr1

array([1, 2, 3, 3, 4])

In [164]:
np.repeat(arr1, 4) #repeating each element 4 times

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4])

In [166]:
np.roll(arr1, shift = 3) #shifting the element 3 times ahead

array([3, 3, 4, 1, 2])

In [167]:
np.diag(arr1) #converting the array into diagonal way

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [170]:
arr = np.random.randint(1, 4, (4, 4))

In [171]:
arr

array([[3, 3, 3, 2],
       [1, 3, 2, 3],
       [3, 3, 1, 2],
       [1, 2, 2, 1]])

In [172]:
np.diag(arr) #here, we extract that diagonals from 2 d array into 1 d array means it can execute in reverse direction also

array([3, 3, 1, 1])

In [169]:
arr

array([[5, 7, 6, 2],
       [9, 6, 6, 6],
       [5, 3, 5, 7]])

In [173]:
#binary operation on array
arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(1, 10, (3, 4))

In [174]:
arr1

array([[6, 9, 4, 4],
       [6, 4, 3, 8],
       [3, 6, 5, 3]])

In [175]:
arr2

array([[8, 4, 2, 2],
       [5, 5, 4, 9],
       [7, 2, 3, 6]])

In [176]:
arr1 + arr2

array([[14, 13,  6,  6],
       [11,  9,  7, 17],
       [10,  8,  8,  9]])

In [177]:
arr1 - arr2

array([[-2,  5,  2,  2],
       [ 1, -1, -1, -1],
       [-4,  4,  2, -3]])

In [178]:
arr1 * arr2

array([[48, 36,  8,  8],
       [30, 20, 12, 72],
       [21, 12, 15, 18]])

In [179]:
arr1 / arr2

array([[0.75      , 2.25      , 2.        , 2.        ],
       [1.2       , 0.8       , 0.75      , 0.88888889],
       [0.42857143, 3.        , 1.66666667, 0.5       ]])

In [180]:
arr1 ** arr2 #make the elements of array2 into power of arr1

array([[  1679616,      6561,        16,        16],
       [     7776,      1024,        81, 134217728],
       [     2187,        36,       125,       729]], dtype=int32)

In [181]:
arr1 % arr2 #finding the modules value of arr1 and arr2 by dividing arr1 by arr2

array([[6, 1, 0, 0],
       [1, 4, 3, 8],
       [3, 0, 2, 3]], dtype=int32)

In [186]:
arr2 % arr1

array([[2, 4, 2, 2],
       [5, 1, 1, 1],
       [1, 2, 3, 0]], dtype=int32)

In [182]:
arr1 & arr2 #and function

array([[0, 0, 0, 0],
       [4, 4, 0, 8],
       [3, 2, 1, 2]], dtype=int32)

In [183]:
arr1 | arr2 #OR function

array([[14, 13,  6,  6],
       [ 7,  5,  7,  9],
       [ 7,  6,  7,  7]], dtype=int32)

In [184]:
~ arr1 #negation function

array([[ -7, -10,  -5,  -5],
       [ -7,  -5,  -4,  -9],
       [ -4,  -7,  -6,  -4]], dtype=int32)

In [185]:
arr1 > arr2 #finding is arr1 is greater than arr2

array([[False,  True,  True,  True],
       [ True, False, False, False],
       [False,  True,  True, False]])

In [193]:
#String function on Array
arr = np.array(["saurabh bhai", "akash anna"])

In [194]:
arr

array(['saurabh bhai', 'akash anna'], dtype='<U12')

In [195]:
np.char.upper(arr) #upper case

array(['SAURABH BHAI', 'AKASH ANNA'], dtype='<U12')

In [196]:
np.char.title(arr) #first letter of each word should capital

array(['Saurabh Bhai', 'Akash Anna'], dtype='<U12')

In [197]:
np.char.capitalize(arr) #only first letter of whole paragraph must capital

array(['Saurabh bhai', 'Akash anna'], dtype='<U12')

In [198]:
#mathematical function on Array
#numpy basically made for working on mathematical laws respect to numerical values.
arr1

array([[6, 9, 4, 4],
       [6, 4, 3, 8],
       [3, 6, 5, 3]])

In [199]:
np.sin(arr1)

array([[-0.2794155 ,  0.41211849, -0.7568025 , -0.7568025 ],
       [-0.2794155 , -0.7568025 ,  0.14112001,  0.98935825],
       [ 0.14112001, -0.2794155 , -0.95892427,  0.14112001]])

In [200]:
np.cos(arr1)

array([[ 0.96017029, -0.91113026, -0.65364362, -0.65364362],
       [ 0.96017029, -0.65364362, -0.9899925 , -0.14550003],
       [-0.9899925 ,  0.96017029,  0.28366219, -0.9899925 ]])

In [201]:
np.tan(arr1)

array([[-0.29100619, -0.45231566,  1.15782128,  1.15782128],
       [-0.29100619,  1.15782128, -0.14254654, -6.79971146],
       [-0.14254654, -0.29100619, -3.38051501, -0.14254654]])

In [202]:
np.tanh(arr1)

array([[0.99998771, 0.99999997, 0.9993293 , 0.9993293 ],
       [0.99998771, 0.9993293 , 0.99505475, 0.99999977],
       [0.99505475, 0.99998771, 0.9999092 , 0.99505475]])

In [203]:
np.log10(arr1)

array([[0.77815125, 0.95424251, 0.60205999, 0.60205999],
       [0.77815125, 0.60205999, 0.47712125, 0.90308999],
       [0.47712125, 0.77815125, 0.69897   , 0.47712125]])

In [204]:
np.exp(arr1)

array([[ 403.42879349, 8103.08392758,   54.59815003,   54.59815003],
       [ 403.42879349,   54.59815003,   20.08553692, 2980.95798704],
       [  20.08553692,  403.42879349,  148.4131591 ,   20.08553692]])

In [205]:
np.sqrt(arr1)

array([[2.44948974, 3.        , 2.        , 2.        ],
       [2.44948974, 2.        , 1.73205081, 2.82842712],
       [1.73205081, 2.44948974, 2.23606798, 1.73205081]])

In [206]:
np.power(arr1, 4)

array([[1296, 6561,  256,  256],
       [1296,  256,   81, 4096],
       [  81, 1296,  625,   81]], dtype=int32)

In [207]:
np.mean(arr1)

5.083333333333333

In [208]:
np.median(arr1)

4.5

In [210]:
np.std(arr1)

1.8911342863183696

In [211]:
np.min(arr1)

3

In [212]:
np.max(arr1)

9

In [213]:
#sorting, searching and counting function.
arr = np.array([3, 24, 53, 22, 2, 1, 4, 6, 43, 77, 344])

In [214]:
arr

array([  3,  24,  53,  22,   2,   1,   4,   6,  43,  77, 344])

In [215]:
np.sort(arr)

array([  1,   2,   3,   4,   6,  22,  24,  43,  53,  77, 344])

In [216]:
np.searchsorted(arr, 5) #after 4

7

In [217]:
np.searchsorted(arr, 2) #after 1

6

In [218]:
arr1 = np.array([0, 345, 543, 0, 0, 0, 0, 0])

In [219]:
np.count_nonzero(arr1)

2

In [221]:
arr

array([  3,  24,  53,  22,   2,   1,   4,   6,  43,  77, 344])

In [222]:
np.where(arr>4) #shows postion of elements

(array([ 1,  2,  3,  7,  8,  9, 10], dtype=int64),)

In [223]:
np.extract(arr>4, arr) #shows actual elements which are grater

array([ 24,  53,  22,   6,  43,  77, 344])

In [224]:
#byte swapping
arr.byteswap()

array([  50331648,  402653184,  889192448,  369098752,   33554432,
         16777216,   67108864,  100663296,  721420288, 1291845632,
       1476460544])

In [225]:
#numpy's copies and views
arr

array([  3,  24,  53,  22,   2,   1,   4,   6,  43,  77, 344])

In [226]:
a = np.copy(arr) #it's make copy with diffrent references

In [227]:
a

array([  3,  24,  53,  22,   2,   1,   4,   6,  43,  77, 344])

In [228]:
b = arr.view() #it referece the 'b' to arr means changes in 'b' will reflect into 'arr'

In [229]:
b

array([  3,  24,  53,  22,   2,   1,   4,   6,  43,  77, 344])

In [230]:
b[0] = 3333

In [231]:
b

array([3333,   24,   53,   22,    2,    1,    4,    6,   43,   77,  344])

In [232]:
arr

array([3333,   24,   53,   22,    2,    1,    4,    6,   43,   77,  344])

In [233]:
#matrix library
import numpy.matlib as nm

In [234]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [235]:
nm.ones((4,3))

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [239]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [249]:
#numpy's linear algebra
arr1 = np.random.randint([[2, 13], [4, 5]])
arr2 = np.random.randint([[2, 13], [2, 5]])

In [250]:
arr1

array([[1, 2],
       [2, 4]])

In [251]:
arr2

array([[0, 4],
       [0, 1]])

In [252]:
np.dot(arr1, arr2)

array([[ 0,  6],
       [ 0, 12]])

In [253]:
arr1 @ arr2

array([[ 0,  6],
       [ 0, 12]])